### ISSUE TITLE
Engine version  = 0.0

### ISSUE THREAD

**Issue by mslinn** [scijava/scripting-clojure#6]
factory.getEngineVersion return "0.0" which is probably an oversight.

**Comment by ctrueden** [comment]
Thanks @mslinn. As a step forward, I changed the abstract base layer to return the version of the containing Maven artifact by default. E.g. for this component, this is currently `0.1.7-SNAPSHOT` plus hash of built commit. This is the same value already given by `getLanguageVersion()`. Note that a new version of `scijava-common` will need to be released, and this component updated to depend on it, in order to guarantee that downstream consumers receive the fix.

If you have a suggestion for a better value to return for Clojure specifically, we can modify the `ClojureScriptLanguage` here to invoke whatever API is used to obtain that value.

**Comment by mslinn** [comment]
This works for me 👍
